### PR TITLE
createOne() adds always only one new row with latest Nette

### PR DESCRIPTION
**Pull request by Edke**
Quite don't know if bug or feature or just I missed something out here, but handler for createOne() funtionality always adds new container only first time ($createDefault + 1).

### CODE REVIEW

**Comment by Edke** [comment]
Looks like this is caused with some BC break while using latest Nette 2.0 stable. Added pull request.

**Comment by fprochazka** [comment]
Thanks!

**Comment by Edke** [comment]
Well, nice :) You closed pull request but also my issue. Pull request was just to migrate sandbox to Nette 2.0 so you can try issue for yourself, not fix  :) But I'm aware that you noticed :) Can you see, why replicator won't add more than single container now ?

**Comment by fprochazka** [comment]
Pull closed it. You might wanna try https://github.com/Kdyby/Framework/blob/master/libs/Kdyby/Forms/Containers/Replicator.php

**Pull request merged**
